### ISSUE TITLE
error with net6

### ISSUE THREAD

**Issue by vuonghung12** [davidnx/NextjsStaticHosting-AspNetCore#1]
Hi, when using your library, I have this error
"NextjsStaticHostingOptions.RootPath must be specified."
Any ideal ?

**Comment by jvasmotta** [comment]
Hi @vuonghung12, you should add the following statement to the WebApplication builder on your Program.cs.

`builder.Services.Configure<NextjsStaticHostingOptions>("your builded static folder from NextJs");`

do not forget to also include: `builder.Services.AddNextjsStaticHosting();`

**Comment by davidnx** [comment]
@vuonghung12 NextjsStaticHostingOptions.RootPath is how you indicate to this library where your Next.js app exported static files are, relative to the content root folder of your published app. Without this information, we wouldn't know where the files are.

You can either set that programmatically in your web app Startup, or you can set it via `appsettings.json`. The demos included in the repo take the second approach. See:

https://github.com/davidnx/NextjsStaticHosting-AspNetCore/blob/031ac63bdeb2cf0da21418e29698ddac96bdd10e/samples/ActualNextjsApp/ActualNextjsApp.Server/appsettings.json#L10-L14

And:
https://github.com/davidnx/NextjsStaticHosting-AspNetCore/blob/031ac63bdeb2cf0da21418e29698ddac96bdd10e/samples/ActualNextjsApp/ActualNextjsApp.Server/Program.cs#L9

**Comment by davidnx** [comment]
Closing as this is believed to be resolved. Please re-open if you run into issues.
