### ISSUE TITLE
NextJs 13 App Router

### ISSUE THREAD

**Issue by ravenet** [davidnx/NextjsStaticHosting-AspNetCore#13]
Hi Team,

I have deployed code with nextjs 13 ap router, it is not working as expected.,

- NextJs13 does not support next export so there are no app.js file
- AppRouter new and it is failed to identify the  publish files using  npm run build.

Thanks

**Comment by davidnx** [comment]
@ravenet thanks for your interest in this library, but your issue description is very vague and doesn't seem to mention anything specific to this project. Please help clarify what problem you faced specifically when using `NextjsStaticHosting-AspNetCore`.

My understanding is that Next.js continues to support static export, and in fact the demo client app included in this repo uses Next.js 13 without issues.

If you are having issues with Next.js and intended to reach the Next.js team, you may want to reach them directly with an issue here: https://github.com/vercel/next.js/issues

Please help clarify, otherwise I will plan to close this in the coming days as non-actionable from my side. Thanks!

**Comment by ravenet** [comment]
@davidnx ,

Thank you for your response and let me explain the issues in better way to be clear.

The library is focusing to deploy the static file hosting and however, the latest NextJs13 if we use the app router, and export the api route functionality is not working in static hosting.

That's the reason i have created this issue to let you know that if you could add feature that use not-static deployment.

I hope this will help and once again thank you for a good library.

Thanks

**Comment by davidnx** [comment]
@ravenet I haven't played with App Router yet, but from reading the docs it looks like static export is still supported. Can you share an example Git repo that shows a minimal repro of your issue? Please include a minimal Next.js app as well as the output it generates when you run `next export`. If that's too much work, please at least share a screenshot showing the folder structure of the outputs you get after `next export`.

For reference, these are the docs I referenced [App Router Incremental Adoption Guide - Next.js](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration)

**Comment by ravenet** [comment]
Hi @davidnx ,

Thank you once again and here sample project attached.
1. please change base url with json place holder 
2. change products  to users.

[ta-next-front.zip](https://github.com/davidnx/NextjsStaticHosting-AspNetCore/files/11594942/ta-next-front.zip)

3. then run next build to publish project to deplopy it
4. copy files from .next folder to anywhere you want to host it.
Thanks

**Comment by davidnx** [comment]
> then run next build to publish project to deplopy it

@ravenet this is the problem. You need to run `next export`, not `next build`. And when I tried using `next export` with your example, Next.js complains with error:

```
- error "next export" does not work with App Router. Please use "output: export" in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
```

Follow the instructions at https://nextjs.org/docs/pages/building-your-application/deploying/static-exports per the error message from Next.js, and you should be good:

![image](https://github.com/davidnx/NextjsStaticHosting-AspNetCore/assets/44079650/5c8f3d27-b8e7-4623-a5aa-dacc27d857b0)

Then, next time you run `next build`, you will get a new `out` folder which you should be able to use with `NextjsStaticHosting-AspNetCore`.

Hope this helps. Closing the issue as this is unrelated to this library, but please reactivate if things still aren't working for any reason. Thanks!
