### ISSUE TITLE
DevServer not starting in VS Code

### ISSUE THREAD

**Issue by MiroValchev** [davidnx/NextjsStaticHosting-AspNetCore#14]
Maybe it's just me but somehow I can't get the DevServer running when running or debugging my app in VS Code. In Visual Studio it's all good. 

Has anyone managed to achieve this?

**Comment by davidnx** [comment]
Submitted a PR that may help get you in the right direction, does this help? https://github.com/davidnx/NextjsStaticHosting-AspNetCore/pull/15

Closing the issue in the hope that this addresses your issue, but please reactivate if you run into issues.
