### ISSUE TITLE
Custom static options

### ISSUE THREAD

**Issue by Velociapcior** [davidnx/NextjsStaticHosting-AspNetCore#3]
Hello, how do I define custom object of StaticFileOptions and inject it int to this middleware? Because right now it seems to be impossible cause of this part:

```
      if (string.IsNullOrEmpty(staticHostingOptions.RootPath))
        throw new InvalidOperationException("NextjsStaticHostingOptions.RootPath must be specified.");
      string physicalRoot = Path.Combine(env.ContentRootPath, staticHostingOptions.RootPath);
      IFileProvider fileProvider = fileProviderFavtory.CreateFileProvider(physicalRoot);
      StaticFileOptions staticFileOptions = new StaticFileOptions();
      staticFileOptions.FileProvider = fileProvider;
      this.StaticFileOptions = staticFileOptions;
```

**Comment by davidnx** [comment]
@Velociapcior please help clarify the scenario and what options you are trying to set in your custom `StaticFileOptions`, it will be useful to figure out the best way to address this. Thanks for your interest in this library.

To help reference this in the future, looks like this is the piece of code you are referring to:
https://github.com/davidnx/NextjsStaticHosting-AspNetCore/blob/031ac63bdeb2cf0da21418e29698ddac96bdd10e/src/NextjsStaticHosting.AspNetCore/Internals/StaticFileOptionsProvider.cs#L24-L34

(side comment: I'd be curious to know where you copied the chunk of code in the original post above, perhaps you used a decompiler? FYI you may hve better luck exploring the raw source in this repo so you can also see useful comments).

**Comment by Velociapcior** [comment]
Hello I probably used resharper decompiler inside visual studio.

Here is the fix I made myself, because I couldn't wait for your response:

```cs
    public StaticFileOptionsProvider(IWebHostEnvironment env, FileProviderFactory fileProviderFavtory, IOptions<NextjsStaticHostingOptions> options, IOptions<StaticFileOptions> staticFileOptions)
    {
        _ = env ?? throw new ArgumentNullException(nameof(env));
        _ = fileProviderFavtory ?? throw new ArgumentNullException(nameof(fileProviderFavtory));
        var o = options?.Value ?? throw new ArgumentNullException(nameof(options));

        if (string.IsNullOrEmpty(o.RootPath))
        {
            throw new InvalidOperationException($"{nameof(NextjsStaticHostingOptions)}.{nameof(NextjsStaticHostingOptions.RootPath)} must be specified.");
        }

        string physicalRoot = Path.Combine(env.ContentRootPath, o.RootPath);
        var fileProvider = fileProviderFavtory.CreateFileProvider(physicalRoot);
        this.StaticFileOptions = staticFileOptions?.Value ?? new StaticFileOptions();

        this.StaticFileOptions.FileProvider = fileProvider;
    }
```

In this change, you can inject StaticFileOptions with Dpeendency Injection and use them inside StaticFileOptions provider.

In other way, I would suggest making StaticFileOptionsProvider a public class, or something similar, because our case shows, that there might be, a need for some specific usecases, which require additional configuration of framework specific services like in this case `UseStaticFiles`.

Overall Your library is really great! Keep up the good work
