### ISSUE TITLE
[Feature Request] Next JS 13

### ISSUE THREAD

**Issue by Meligy** [davidnx/NextjsStaticHosting-AspNetCore#6]
Hello.

Have you tried checking how this would work with the new changes in Next JS 13?

Thanks.

**Comment by davidnx** [comment]
@Meligy I upgraded the sample client app to the latest Next.js 13.1.6, works fine as far as I can tell (see: #12).

Are there specific changes in Next.js 13 that you are particularly worried about? I expect everything will continue to work as long as you can export your Next.js app (`next export`). At least in the trivial demo app, that continues to work.

**Comment by Meligy** [comment]
Thanks a lot. I was just really checking if it'd be different, because I'm seeing online that Next 13 is a it of a different beast, but glad to see it's not a massive change. Thanks heaps.
