### ISSUE TITLE
Top Level Statement app.Map overrides all other maps with DevServer enabled.

### ISSUE THREAD

**Issue by ThomasAunvik** [davidnx/NextjsStaticHosting-AspNetCore#7]
Due to [ASP-0014](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0014?view=aspnetcore-7.0) suggestion, it wants to use top level statement.

From:
```cs
app.UseEndpoints(endpoints =>
{
    endpoints.MapNextjsStaticHtmls();
});
```
to
```cs
app.MapNextjsStaticHtmls();
```

That is fine. However.

When combined with using Maps' like MapControllers, the UseEndpoints work, but not the other, as in it redirects to nextjs, and gives out a 404.

Works:
```cs
app.MapControllers();

app.UseEndpoints(endpoints =>
{
    endpoints.MapNextjsStaticHtmls();
});
```

Controller does not work:
```cs
app.MapControllers();
app.MapNextjsStaticHtmls();
```

**Comment by davidnx** [comment]
Thanks for reporting @ThomasAunvik! Fixed and I will publish a new Nuget soon.
